### ISSUE TITLE
Problem with `Getting Started` instructions

### ISSUE THREAD

**Issue by patrickbdev** [frida/frida-swift-bridge#1]
At present, the instructions are:
```
$ npm run install
$ npm run build
$ frida <process name> -l _agent.js
```
Using the latest version of npm (`7.22.0`).

Steps:
1. `cd` into repo directory
2. execute `npm run install`

Output:
```
npm ERR! Missing script: "install"
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     npm uninstall # Remove a package
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

I have tried:
1. `npm install` which seemed to install the dependencies.
2. `npm run build`
3. `frida -U {app} --no-pause -l _agent.js` 

Output:
```
Usage: frida [options] target

frida: error: [Errno 2] No such file or directory: '/Users/xxx/git/frida-swift-bridge/_agent.js'
```

**Comment by hot3eed** [comment]
The Swift bridge is actually bundled with Frida by default as of Frida `15.1.0`, that means there's no extra setup steps needed, just install Frida and you're good to go. Thanks for the heads-up! Will update that the README.

**Comment by patrickbdev** [comment]
Amazing, thanks @hot3eed!
